using System;
using System.Windows.Controls;
using System.Windows.Media.Imaging;

namespace Therondels
{
    public partial class LesProfessionnels
    {
        private const string Professionnel = "Agriculture, agro-alimentaire, tourisme, restauration, artisanat… l’activité économique à Thérondels n’a rien de symbolique. Derrière les richesses produites, ce sont des emplois au village et donc de la vie.\n\nL’agriculture continue de jouer un rôle dominant. C’est l’un des pivots de l’activité avec plus de quarante agriculteurs.\n\nThérondels, station verte de vacances, est un bourg centre et possède tous les services indispensables : médecin, pharmacien, supérette, coiffeur, boulangerie-épicerie, tabac-presse, cafés, station service, borne camping-car, Agence Postale, garage auto, hôtel-restaurant ainsi que plusieurs gîtes ruraux.\n\nIl faut citer également la transformation du lait produit par les éleveurs locaux dans la coopérative laitière locale. Il en sort un des plus délicieux Cantal AOC au lait cru.\n\nLa commune compte également des spécialistes du bois qui, des boiseries de château aux parquets en chênes, en passant par les « House-Boat », continuent de travailler, dans le respect des règles de l’art,  des produits en bois faits pour durer.\n\nLa production électrique, d’origine hydraulique est un autre élément fondamental de l’économie du Carladez. La Truyère est l’une des rivières les plus hydro-électrifiées de France. La construction du barrage de Sarrans en 1933 a modifié le paysage de la région Ce dernier retient les eaux sur 35 kilomètres de long, noyant près de 1000 hectares de terre. Le village de Laussac est devenu une presqu’île et un lieu idyllique pour passer ses vacances.";
        private const string Agriculture = "Liste des agriculteurs de la commune :\n\n - AJALBERT Jeanine – Le Crouzet – 12600 THERONDELS\n - ANGELVY Antoine – Gorse – 12600 THERONDELS\n - BELARD Denis – Frons -  12600 THERONDELS\n - BELARD Michel – Faliès – 12600 THERONDELS\n - BELARD Pierre-Antoine – Frons – 12600 THERONDELS\n - BOUDIAS Patrick – Doux-Albats – 12600 THERONDELS\n - BURGUIERE Renée – Le Meyniel – 12600 THERONDELS\n - CAZES Alain – Marut – 12600 THERONDELS\n - CAZES Elie -  Doux-Albats – 12600 THERONDELS\n - CHAMPAGNAC Gérard – Faliès – 12600 THERONDELS\n - CHRESTEIL Claude – Pervilhergues – 12600 THERONDELS\n - COUZI Pierre – Ladinhac – 12600 THERONDELS\n - CUSSET Jean-Claude – Mandilhac – 12600 THERONDELS\n - DELBES Michel – Le Bourg – 12600 THERONDELS\n - EARL BELARD Philippe – Faliès – 12600 THERONDELS\n - EARL GUIMONTHEIL Jean-Michel – Faliès – 12600 THERONDELS\n - EARL de Campheyt – SOULIE Sebastien – Campheyt – 12600 THERONDELS\n - GAEC de Secroup – BELARD Bernard – Secroup – 12600 THERONDELS\n - GAEC de la Source – ANDRIEU Christiane & Yvette MABIT – Doux-Alabts – 12600 THERONDELS\n - GAEC du MEYNIEL – ALRIC Jean-Luc – Le Meyniel – 12600 THERONDELS\n - EARL du Moulin de Jacques – LAFON Cyril – Ladinhac – 12600 THERONDELS\n - GAEC ROUCHES – ROUCHES Christophe – Le Montheil – 12600 THERONDELS\n - GARREL Christian – Pervilhergues – 12600 THERONDELS\n - LADOUX Jean-Luc – Nigresserre – 12600 THERONDELS\n - LADOUX Serge – Septfonds – 12600 THERONDELS\n - LAMBEL Marinette – Doux-Albats – 12600 THERONDELS\n - NOLORGUES Alain – Le Bousquet – 12600 THERONDELS\n - OUVRIER André – Pervilhergues – 12600 THERONDELS\n - PAILHOL Elie – Banes – 12600 THERONDELS\n - POUDEVIGNE Philippe – CAmpheyt – 12600 THERONDELS\n - RECOULES Gilbert – Le Bourg – 12600 THERONDELS\n - RIGAL Jacky – Frons – 12600 THERONDELS\n - EARL de Mandilhac – SOULENQ Sylvie – Mandilhac – 12600 THERONDELS\n - SOULENQ Gérard – Gorse – 12600 THERONDELS\n - VERDIER Claude – Mandilhac – 12600 THERONDELS\n - VERDIER Nicolas – Pervilhergues – 12600 THERONDELS\n - VEYRES Alain – Le Meyniel – 12600 THERONDELS\n - VEYRES Gilbert – Roumégous – 12600 THERONDELS";
        private const string Artisanat = "La commune de Thérondels possède de nombreux artisans reconnus pour leur savoir faire.\n\n - AMEILHAUD Alain – Zone artisanale – couverture, zinguerie et ramonage – 04 71 73 41 69 ou 06 38 83 32 69\n - Aveyron Bois Création – Zone artisanale – 05 65 51 64 70 ou 05 65 66 14 06\n - Coopérative Fromagère – Zone artisanale – 05 65 66 02 88\n - CROZES Sandrine – Graphiste – 06 23 02 84 69 – http://www.rue-graphique.com \n - DRI Laëtitia – Maquettiste http://dri.laetitia.free.fr/ \n - FEUILLET Michel (peinture – papier peint – revêtement de sol) – Faliès – 05 65 66 11 64\n - FROMENT Jérôme (travaux agricoles et ruraux) - La croix de la Molède – 05 65 66 26 70 ou 06 74 50 27 19\n - GUIBAL Michel – Le bourg – Petits travaux intérieurs et extérieurs – 06 79 23 35 27\n - LAMBEL Stéphane – Taxi – Doux-albats – 05 65 48 67 15 ou 06 78 97 62 48\n - LEMOUZY Francis (menuiserie) – Doux-albats – 05 65 66 26 75 ou 06 76 86 99 35\n - MOULIAC SARL (matériel agricole) – Z.A. Labounitio – 05 65 66 19 80\n - Parqueterie SOULENQ – Gorse – 05 65 66 20 87  / http://www.soulenq.com/ \n - ROQUIER Vincent (électricité) – 05 65 66 02 98\n - SARL POUJOULY-LABERTRANDIE (maçonnerie) – 7 rue la Lato – 05 65 66 02 80 ou 06 81 68 76 89 / http://www.labertrandie-maconnerie-therondels.fr/ \n - Thérondels Automobiles – Zone Artisanale – 05 65 66 14 26 ou 05 65 66 22 60";
        private const string Commerces = "Le village de Thérondels, bourg centre de la Commune de Thérondels, territoire le plus septentrional du département de l’aveyron et de la Région Midi-pyrénées, possède de nombreux commerces et services, en témoigne la liste présentée ci dessous:\n\n - Adom’ PC - BRIQUEZ Franck  – Lagarrige – 15230 MALBO – Tél : 06  48 73 58 24 - Dépannage informatique à domicile, formation, vente, création de site internet - Site internet : http://www.adom-pc.com/ \n - Agence Postale Communale, Le Bourg. Tél. : 05 65 66 48 26 - Lundi, mercredi et jeudi de 13h30 à 16h30. Mardi et vendredi de 9h15 à 12h15.\n - Bar « La Gentiane » – BELLANGER Vincent – 05 65 48 66 79\n - Bar « chez Tintin » – MEYNIEL Antonin – Le Bourg\n - Bar « L’Oustal » – Le Bourg – TARRISSE Daniel – 05 65 66 12 37\n - Bar, café, snack « Le Chalet du Lac » – Presqu’île de Laussac – TARRISSE Daniel – 05 65 66 04 58\n - Bar « Les Acacias » – VEYLET Bernard – 05 65 66 18 15\n - BOILE Gérard – Médecin - Le Bourg – 05 65 66 05 65\n - Camping La Source – Presqu’île de Laussac – 05 65 66 05 62\n - Coiffure et Institut de beauté HORWATH – Le Bourg – 05 65 66 08 55 / 06 08 00 74 29 Site internet : http://www.artisans12.fr/horwath-institut.html \n - DUTREVIS Jean-Pierre – Boucherie charcuterie – Le Bourg – 04 71 23 33 04\n - Hôtel MIQUEL – Le Bourg – 05 65 66 02 72\n - LABORIE Jean-Paul (Boulangerie-pâtisserie) – Le Bourg – 05 65 66 02 93\n - Restaurant La Source – Presqu’île de Laussac – 05 65 66 60 40\n - Pharmacie TERNAT - Le Bourg – 05 65 66 18 83\n - Supérette Vival – DALAT-RICHARD – 05 65 66 21 29\n - Station service – VEYLET Bernard – 05 65 66 18 15";
        private const string Fromage1 = "Fabrication et VENTE du Cantal A.O.C et du « THERONDELS » au lait cru, et de la tome fraîche.\nOuvert le vendredi matin toute l’année de 10h à 12h et les samedis matin durant les vacances scolaires de 10h à 12h.\nVisites guidées gratuites , dégustation et vente.\nTél. : 05 65 66 02 88 / Fax. : 05 65 66 63 03";
        private const string Fromage2 = "Assemblée générale : 2012, une année d’exception\n\nLe chiffre d’affaire  « produits transformés » connaît une croissance record avec une progression de près de 50% par rapport à l’exercice précédent, dépassant 3,5 millions d’euros. Une analyse un peu plus détaillée montre:\n - la bonne tenue des ventes de fromage Cantal, + 6%,\n - une progression très importante pour l’Aligot qui voit son chiffre d’affaires plus que doubler en un an,\n - une dynamique des volumes de tome fraîche pasteurisée, + 15%.\n - un niveau de collecte de 3.747.000 litres, + 8.7%.\navec pour conséquence un résultat positif qui permet de ristourner 10 € pour 1000 litres aux adhérents, une première à la coopérative de Thérondels!.\n\nUne reconnaissance : une médaille d’or au concours de fromages d’ESPALION, pour « LE THERONDELS », fabriqué en Carladez à partir de lait cru sous cahier des charges spécifiques, sans ensilage (extrait du rapport moral du Président Raymond Cayzac, AG  du 17 mai 2013)";
        private const string Servicesmedicaux = "On retrouve au bourg de Thérondels une pharmacie et un cabinet médical, ce qui est est assez rare pour une commune rurale de moins de 500 habitants.\n\n - Le Docteur Gérard BOILE reçoit ses patients au cabinet médical au sein de la Résidence 1948, route de Laussac.\n - M et Mme TERNAT Jacques gère la pharmacie qui est située : Résidence 1948 (à côté du cabinet médical).";

        public LesProfessionnels()
        {
            InitializeComponent();
            this.FillText();
        }

        private void FillText()
        {
            textBoxProfessionnels.Text = Professionnel;
            textBoxAgriculture.Text = Agriculture;
            textBoxArtisanat.Text = Artisanat;
            textBoxCommerces.Text = Commerces;
            textBoxFromage1.Text = Fromage1;
            textBoxFromage2.Text = Fromage2;
            textBoxServicesMedicaux.Text = Servicesmedicaux;
        }

        private void ClickImage(object sender, System.Windows.Input.GestureEventArgs e)
        {
            var imageUrl = ((BitmapImage)((Image)e.OriginalSource).Source).UriSource;
            var sent = imageUrl.ToString().Replace("/therondels;component/", "").Replace("/", "~");
            NavigationService.Navigate(new Uri("/PicturePage.xaml?selectedItem=" + sent, UriKind.Relative));
        }
    }
}